/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2022-11-12 21:56:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<!-- Latest compiled and minified CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- jQuery library -->\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Popper JS -->\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Latest compiled JavaScript -->\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Banquito Fiel - Login</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"height: 100vh;\" class=\"bg-light\">\r\n");
      out.write("\t\t<form method=\"get\" action=\"ServletLogin\" class=\"h-100 d-flex align-content-center\">\r\n");
      out.write("\t\t\t<div class=\"card w-50 m-auto d-flex flex-column shadow\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-header text-center\">Login</h5>\r\n");
      out.write("\t\t\t\t<div class=\"w-75 container p-4 border border-0\">\r\n");
      out.write("\t\t\t\t\t<div class=\"d-flex flex-column mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"pb-2\">Usuario</span>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"txtUsuario\" class=\"border-top-0 border-right-0 border-left-0\" \r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-color: #efefef;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"d-flex flex-column mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"pb-2\">Constraseña</span>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"txtPassword\" class=\"border-top-0 border-right-0 border-left-0\" \r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-color: #efefef;\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary m-auto w-50 d-block\" name=\"btnLogin\" value=\"Ingresar\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t         <div style=\"width:100%;height:50px;float:center\">\r\n");
      out.write("\t\t         <div style=\"width:100%;height:50px;float:center\">\r\n");
      out.write("\t\t         <div style=\"width:100%;height:50px;float:center\">\r\n");
      out.write("\t\t         ");
 if (request.getAttribute("error")!=null){ 
      out.write("\r\n");
      out.write("\t\t         \t<p style=\"text-align:center;font-size: xx-small; color: red;\"><strong>Ingrese un usuario y contraseña correcta</strong></p>\r\n");
      out.write("\t\t         ");
} 
      out.write("\r\n");
      out.write("\t\t         ");
 if (request.getAttribute("cad")!=null){ 
      out.write("\r\n");
      out.write("\t\t         \t<h5>");
      out.print(request.getAttribute("cad"));
      out.write("</h5>\r\n");
      out.write("\t\t         ");
} 
      out.write("\r\n");
      out.write("\t\t         </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--session.setAttribute(\"TipoUsurio\", \"usuario\");\r\n");
      out.write("\tif(request.getParameter(\"btnLogin\")!=null)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tString usuario = request.getParameter(\"txtUsuario\");\r\n");
      out.write("\t\tString apellido = request.getParameter(\"txtPassword\");\r\n");
      out.write("\t\tif(usuario.contentEquals(\"admin\")){\r\n");
      out.write("\t\t\tsession.setAttribute(\"TipoUsurio\", \"admin\");\r\n");
      out.write("\t\t\tresponse.sendRedirect(\"ServletAdmin?Param=1\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tresponse.sendRedirect(\"Cuenta1.jsp\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsession.setAttribute(\"nombreUsurio\", usuario);\r\n");
      out.write("\t}-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
